### ISSUE TITLE
Contact section.

### ISSUE THREAD

**Issue by franciscoPonceDev** [41hulk/micro-portfolio#4]
## Suggestions

- [x]  You can use `background-image` in this section to add the background.

- [x]  Position the text on the left side of section and the form to the right side.

**Comment by awaisanwar544** [comment]
[ ] Try using separate `div`'s with `position: absolute` to position background images

**Comment by awaisanwar544** [comment]
- [ ]  Try using separate div's with position: absolute to position background images

**Comment by 41hulk** [comment]
Thanks, team for the feedbacks
